/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AppointmentRequest {
  'id' : bigint,
  'branch' : Branch,
  'message' : [] | [string],
  'preferredDate' : string,
  'preferredTime' : TimePreference,
  'timestamp' : bigint,
  'patientName' : string,
  'phoneNumber' : string,
}
export type Branch = { 'koduvayur' : null } |
  { 'yakkara' : null } |
  { 'puthur' : null };
export type TimePreference = { 'morning' : null } |
  { 'evening' : null } |
  { 'noPreference' : null } |
  { 'afternoon' : null };
export interface _SERVICE {
  'convertBranchToText' : ActorMethod<[Branch], string>,
  'convertTimePrefToText' : ActorMethod<[TimePreference], string>,
  'getAllAppointmentRequests' : ActorMethod<[], Array<AppointmentRequest>>,
  'submitAppointmentRequest' : ActorMethod<
    [string, string, Branch, string, TimePreference, [] | [string]],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];