/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Branch = IDL.Variant({
  'koduvayur' : IDL.Null,
  'yakkara' : IDL.Null,
  'puthur' : IDL.Null,
});
export const TimePreference = IDL.Variant({
  'morning' : IDL.Null,
  'evening' : IDL.Null,
  'noPreference' : IDL.Null,
  'afternoon' : IDL.Null,
});
export const AppointmentRequest = IDL.Record({
  'id' : IDL.Nat,
  'branch' : Branch,
  'message' : IDL.Opt(IDL.Text),
  'preferredDate' : IDL.Text,
  'preferredTime' : TimePreference,
  'timestamp' : IDL.Int,
  'patientName' : IDL.Text,
  'phoneNumber' : IDL.Text,
});

export const idlService = IDL.Service({
  'convertBranchToText' : IDL.Func([Branch], [IDL.Text], []),
  'convertTimePrefToText' : IDL.Func([TimePreference], [IDL.Text], []),
  'getAllAppointmentRequests' : IDL.Func(
      [],
      [IDL.Vec(AppointmentRequest)],
      ['query'],
    ),
  'submitAppointmentRequest' : IDL.Func(
      [IDL.Text, IDL.Text, Branch, IDL.Text, TimePreference, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Branch = IDL.Variant({
    'koduvayur' : IDL.Null,
    'yakkara' : IDL.Null,
    'puthur' : IDL.Null,
  });
  const TimePreference = IDL.Variant({
    'morning' : IDL.Null,
    'evening' : IDL.Null,
    'noPreference' : IDL.Null,
    'afternoon' : IDL.Null,
  });
  const AppointmentRequest = IDL.Record({
    'id' : IDL.Nat,
    'branch' : Branch,
    'message' : IDL.Opt(IDL.Text),
    'preferredDate' : IDL.Text,
    'preferredTime' : TimePreference,
    'timestamp' : IDL.Int,
    'patientName' : IDL.Text,
    'phoneNumber' : IDL.Text,
  });
  
  return IDL.Service({
    'convertBranchToText' : IDL.Func([Branch], [IDL.Text], []),
    'convertTimePrefToText' : IDL.Func([TimePreference], [IDL.Text], []),
    'getAllAppointmentRequests' : IDL.Func(
        [],
        [IDL.Vec(AppointmentRequest)],
        ['query'],
      ),
    'submitAppointmentRequest' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          Branch,
          IDL.Text,
          TimePreference,
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };