/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface AppointmentRequest {
    id: bigint;
    branch: Branch;
    message?: string;
    preferredDate: string;
    preferredTime: TimePreference;
    timestamp: bigint;
    patientName: string;
    phoneNumber: string;
}
export enum Branch {
    koduvayur = "koduvayur",
    yakkara = "yakkara",
    puthur = "puthur"
}
export enum TimePreference {
    morning = "morning",
    evening = "evening",
    noPreference = "noPreference",
    afternoon = "afternoon"
}
export interface backendInterface {
    convertBranchToText(branch: Branch): Promise<string>;
    convertTimePrefToText(timePref: TimePreference): Promise<string>;
    getAllAppointmentRequests(): Promise<Array<AppointmentRequest>>;
    submitAppointmentRequest(patientName: string, phoneNumber: string, branch: Branch, preferredDate: string, preferredTime: TimePreference, message: string | null): Promise<void>;
}
import type { AppointmentRequest as _AppointmentRequest, Branch as _Branch, TimePreference as _TimePreference } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async convertBranchToText(arg0: Branch): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.convertBranchToText(to_candid_Branch_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.convertBranchToText(to_candid_Branch_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async convertTimePrefToText(arg0: TimePreference): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.convertTimePrefToText(to_candid_TimePreference_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.convertTimePrefToText(to_candid_TimePreference_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getAllAppointmentRequests(): Promise<Array<AppointmentRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAppointmentRequests();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAppointmentRequests();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitAppointmentRequest(arg0: string, arg1: string, arg2: Branch, arg3: string, arg4: TimePreference, arg5: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitAppointmentRequest(arg0, arg1, to_candid_Branch_n1(this._uploadFile, this._downloadFile, arg2), arg3, to_candid_TimePreference_n3(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n13(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitAppointmentRequest(arg0, arg1, to_candid_Branch_n1(this._uploadFile, this._downloadFile, arg2), arg3, to_candid_TimePreference_n3(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n13(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
}
function from_candid_AppointmentRequest_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppointmentRequest): AppointmentRequest {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Branch_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Branch): Branch {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_TimePreference_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TimePreference): TimePreference {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    branch: _Branch;
    message: [] | [string];
    preferredDate: string;
    preferredTime: _TimePreference;
    timestamp: bigint;
    patientName: string;
    phoneNumber: string;
}): {
    id: bigint;
    branch: Branch;
    message?: string;
    preferredDate: string;
    preferredTime: TimePreference;
    timestamp: bigint;
    patientName: string;
    phoneNumber: string;
} {
    return {
        id: value.id,
        branch: from_candid_Branch_n8(_uploadFile, _downloadFile, value.branch),
        message: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.message)),
        preferredDate: value.preferredDate,
        preferredTime: from_candid_TimePreference_n11(_uploadFile, _downloadFile, value.preferredTime),
        timestamp: value.timestamp,
        patientName: value.patientName,
        phoneNumber: value.phoneNumber
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    morning: null;
} | {
    evening: null;
} | {
    noPreference: null;
} | {
    afternoon: null;
}): TimePreference {
    return "morning" in value ? TimePreference.morning : "evening" in value ? TimePreference.evening : "noPreference" in value ? TimePreference.noPreference : "afternoon" in value ? TimePreference.afternoon : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    koduvayur: null;
} | {
    yakkara: null;
} | {
    puthur: null;
}): Branch {
    return "koduvayur" in value ? Branch.koduvayur : "yakkara" in value ? Branch.yakkara : "puthur" in value ? Branch.puthur : value;
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AppointmentRequest>): Array<AppointmentRequest> {
    return value.map((x)=>from_candid_AppointmentRequest_n6(_uploadFile, _downloadFile, x));
}
function to_candid_Branch_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Branch): _Branch {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_TimePreference_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TimePreference): _TimePreference {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Branch): {
    koduvayur: null;
} | {
    yakkara: null;
} | {
    puthur: null;
} {
    return value == Branch.koduvayur ? {
        koduvayur: null
    } : value == Branch.yakkara ? {
        yakkara: null
    } : value == Branch.puthur ? {
        puthur: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TimePreference): {
    morning: null;
} | {
    evening: null;
} | {
    noPreference: null;
} | {
    afternoon: null;
} {
    return value == TimePreference.morning ? {
        morning: null
    } : value == TimePreference.evening ? {
        evening: null
    } : value == TimePreference.noPreference ? {
        noPreference: null
    } : value == TimePreference.afternoon ? {
        afternoon: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
